docker_build(
  'vigneshvicky97/devops-directive-docker-course-client-react-nginx', 
  './',
)
k8s_yaml('../../07-deploying-demo-application/client-react/Deployment.yaml')
k8s_resource('client-react-nginx', port_forwards=8080)
