# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: api-golang
#   namespace: demo-app
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
# spec:
#   ingressClassName: cilium
#   rules:
#     - host: k8s.vigneshsdev.uk
#       http:
#         paths:
#           - path: /api/golang(/|$)(.*)
#             pathType: Prefix
#             backend:
#               service:
#                 name: api-golang
#                 port:
#                   number: 8000