# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: client-react-nginx
#   namespace: demo-app
# spec:
#   ingressClassName: cilium
#   rules:
#     - host: k8s.vigneshsdev.uk
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: client-react-nginx
#                 port:
#                   number: 8080